#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pisces_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      auto-commit: false
    type: com.alibaba.druid.pool.DruidDataSource
#服务端口
server:
  port: 8888
#mybatis mapper包、实体类包
mybatis:
  mapper-locations: classpath:mapper/userMappper.xml
  type-aliases-package: com.iblog.entity
#分页插件pagehelper
pagehelper:
  #数据库连接类型
  helper-dialect: mysql
  #当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），
  #会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
  #自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，
  #用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，
  #不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;
  #reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql
